apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-full
spec:
  selector:
    matchLabels:
      app: ds-full
  template:
    metadata:
      labels:
        app: ds-full
    spec:
      containers:
      - name: ds-full
        image: webofmars/go-whoami
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ds-full
spec:
  type: LoadBalancer
  selector:
    app: ds-full
  ports:
  - port: 80
    targetPort: 3000
