apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-with-pvc-1
spec:
  replicas: 3
  serviceName: sts-with-pvc-1
  selector:
    matchLabels:
      app: sts-with-pvc-1
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: sts-with-pvc-1
      labels:
        app: sts-with-pvc-1
    spec:
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
  template:
    metadata:
      labels:
        app: sts-with-pvc-1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sts-with-pvc
            topologyKey: "topology.kubernetes.io/region"
      containers:
      - name: sts-with-pvc-1
        image: alpine
        command: ["tail", "-f", "/dev/null"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
